### ISSUE TITLE
license

### ISSUE THREAD

**Issue by yogurtearl** [jbrains/TrackEveryPenny#4]
I bought the book. :-) 
Can you add a license to the code? ( hopefully something commercial friendly )

**Comment by jbrains** [comment]
Which licence would best suit you?

**Comment by yogurtearl** [comment]
Of course, I am not a lawyer.

While not really a license per se, Public domain CC0 ( http://creativecommons.org/publicdomain/zero/1.0/ ) would be great. Otherwise, Apache 2, seems to be a popular choice.

**Comment by jbrains** [comment]
Why is a commercial-friendly licence important to you? Do you intend to sell the code in my book somehow?

**Comment by yogurtearl** [comment]
I don't have any plans to sell the code ( or even use the code directly unless I find something particularly useful and reusable ). I am just overly careful about reading any code that in not under a commercial friendly license and like to know the license ahead of time. :)

**Comment by jbrains** [comment]
When you say "commercial friendly licence", what about specifically "commercial friendly" is important to you? Right now, I don't understand why that matters. You want to be sure that, if you find something, that you can use it?

**Comment by yogurtearl** [comment]
As they say, "I am not a lawyer", so maybe I off base here, but...

It may never matter, but if I find a utility class that would be useful in a closed source project or as an addition to another open source project it would be helpful to have a license on this.

Good point on "Commercial friendly", as it is not very precise and probably a matter of opinion. I would consider Apache 2 "commercial friendly" but not GPLv3. ( GPLv3 requires derived works to be distributed with source. )

Also, a lot of Android related open source is Apache 2, so it would make it easy to reuse pieces of this in combination with other open source while keeping the licensing simple.

Anyway, thanks for taking the time to respond.

**Comment by jbrains** [comment]
I've added a license to the master branch. I'll merge into published when next I publish.
